### ISSUE TITLE
problem with hpfeed

### ISSUE THREAD

**Issue by flori07** [mushorg/glastopf#130]
Hey all, I have a problem with hpfeed when running Glastopf
Here is what i get:

 2013-09-19 22:54:19,599 (pyhpfeeds) connecting to hpfriends.honeycloud.net:20000
2013-09-19 22:54:22,640 (pyhpfeeds) FeedException while connecting: Could not connect to broker [hpfriends.honeycloud.net].

Does anyone have an idea why?
 Thanks a lot, Flori

**Comment by brendan004** [comment]
Hello. I see it's been a LONG time since this was addressed. I noticed that  http://map.honeynet.org/ no longer populates data. I've been trying to get Glastopf to work and run in to the same issues as we have seen here:
error: [Errno 111] Connection refused
2016-02-24 17:18:13,537 (pyhpfeeds) FeedException while connecting: Could not connect to broker [hpfriends.honeycloud.net].
2016-02-24 17:18:33,561 (pyhpfeeds) connecting to hpfriends.honeycloud.net:20000
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 344, in connect
    raise error(err, strerror(err))
error: [Errno 111] Connection refused
2016-02-24 17:18:33,745 (pyhpfeeds) FeedException while connecting: Could not connect to broker [hpfriends.honeycloud.net].

Is this project dead in the water? Glastopf comes with Honeydrive3 so I thought it would run out of the box. It does not. I also followed your installation instructions found here:
https://github.com/mushorg/glastopf/blob/master/docs/source/installation/installation_ubuntu.rst

I have also commented out hpfeeds section in /honeydrive/glastopf-honeypot/glastopf.cfg:
[hpfeed]
#enabled = True
#host = hpfriends.honeycloud.net
#port = 20000
#secret = 3wis3l2u5l7r3cew
# channels comma separated
#chan_events = glastopf.events
#chan_files = glastopf.files
#ident = x8yer@hp1

Thoughts?
