### ISSUE TITLE
Getting this error after running glastopf-runner first time.

### ISSUE THREAD

**Issue by adwiteeya** [mushorg/glastopf#191]
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 5, in <module>
    pkg_resources.run_script('Glastopf==3.1.3-dev', 'glastopf-runner')
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 10, in <module>
    from gevent.wsgi import WSGIServer
  File "/usr/local/lib/python2.7/dist-packages/gevent/**init**.py", line 36, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 14, in <module>
    You can get a newer version of greenlet from http://pypi.python.org/pypi/greenlet/''' % (greenlet_version, ))
ImportError: Your version of greenlet (0.3.1) is too old (required >= 0.3.2)
             You can get a newer version of greenlet from http://pypi.python.org/pypi/greenlet/

**Comment by irimia** [comment]
pip install --upgrade greenlet
