### ISSUE TITLE
Error messages after installation

### ISSUE THREAD

**Issue by zappe** [mushorg/glastopf#204]
We noticed some error messages when installing on Ubuntu 14.10.
Is there some compatability issues for that version?
Since it seems to work fine in 12.04

``` Python
/opt/BFR# tail -n 30 /root/.pip/pip.log 

    return _do_download(version, download_base, to_dir, download_delay)

  File "distribute_setup.py", line 132, in _do_download

    _build_egg(egg, tarball, to_dir)

  File "distribute_setup.py", line 123, in _build_egg

    raise IOError('Could not build the egg.')

IOError: Could not build the egg.
```

---

Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/glastopf
Exception information:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/glastopf
```

**Comment by glaslos** [comment]
It seems to be that your python ssl library and  urllib3 are not compatible. Do you need the `urllib3` module installed? `requests` ships it's own version of it. Remove `ssl`, `urllib3` and `requests`. Then install `requests`. Make sure the files are properly removed. After uninstalling make sure that importing causes an import error. After installation, try:
```python
import requests
r = requests.get('https://google.com')
```
