### ISSUE TITLE
Problem sensor_addr when using surfcertids module

### ISSUE THREAD

**Issue by ramous** [mushorg/glastopf#206]
Hello, I'm using glastopf 3.1.3 and I have problem in logging to surfnetids using the surfcertids module, which is, when I start glastopf, I receive this kind error log:
normally for the value of "sensor_addr" it wait to read "inet" data but it receives a character value which is "sensor2.honey.com" 

--------------------|  error in glastopf log |-------------------

2014-11-19 09:05:52,174 (glastopf.glastopf) 66.249.x.x requested GET /publisher/%5C%22smb.conf%5C%22 on sensor2.honey.com:80
2014-11-19 09:05:52,327 (glastopf.glastopf) Error while logging using <glastopf.modules.reporting.auxiliary.log_surfcertids.LogSURFcertIDS object at 0x9b2856c>: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/glastopf/glastopf.py", line 130, in post_processer
    _logger.insert(attack_event)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/glastopf/modules/reporting/auxiliary/log_surfcertids.py", line 118, in insert
    self.options["atype"]
InternalError: current transaction is aborted, commands ignored until end of transaction block

 
--------------------| postgresql log |--------------------

2014-11-19 08:59:42 CET LOG:  statement: SELECT surfids3_attack_add(0, '66.249.x.x', '38925', 'sensor2.honey.com', '80', NULL, 3);
2014-11-19 08:59:42 CET STATEMENT:  SELECT surfids3_attack_add(0, '66.249.x.x', '38925', 'sensor2.honey.com', '80', NULL, 3);
2014-11-19 08:59:42 CET LOG:  statement: SELECT surfids3_attack_add(0, '66.249.x.x', '38925', 'sensor2.honey.com', '80', NULL, 3);
2014-11-19 08:59:42 CET STATEMENT:  SELECT surfids3_attack_add(0, '66.249.x.x', '38925', 'sensor2.honey.com', '80', NULL, 3);

 
But if I change the value of "attack_event.sensor_addr", it works, but I face another kind of problem with the destination address, which will be "127.0.0.1", and because I use network interface with multiple IP address, I need to log the real destination of each attack.

--------------------| glastopf.py config |------------------------

 def handle_request(self, raw_request, addr, sensor_addr):

        attack_event = attack.AttackEvent()
        attack_event.raw_request = raw_request
        #attack_event.sensor_addr = sensor_addr
        attack_event.sensor_addr = ('127.0.0.1', 80)

-----------------------------| the new log |------------------------------
2014-11-18 17:46:48 CET LOG:  statement: BEGIN
2014-11-18 17:46:48 CET LOG:  duration: 0.582 ms
2014-11-18 17:46:48 CET LOG:  statement: SELECT surfids3_attack_add(0, '193.95.x.x', '37174', '127.0.0.1', '80', NULL, 3);
2014-11-18 17:46:48 CET LOG:  duration: 1.823 ms
2014-11-18 17:46:48 CET LOG:  statement: SELECT surfids3_detail_add((0), '127.0.0.1', 60, 'None');
2014-11-18 17:46:48 CET LOG:  duration: 1.138 ms
2014-11-18 17:46:48 CET LOG:  statement: SELECT surfids3_detail_add((0), '127.0.0.1', 61, 'http://196.y.y.y/index');
2014-11-18 17:46:48 CET LOG:  duration: 1.295 ms
2014-11-18 17:46:48 CET LOG:  statement: SELECT surfids3_detail_add((0), '127.0.0.1', 62, 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0');
2014-11-18 17:46:48 CET LOG:  duration: 1.456 ms
2014-11-18 17:46:48 CET LOG:  statement: SELECT surfids3_detail_add((0), '127.0.0.1', 63, '196.y.y.y');
2014-11-18 17:46:48 CET LOG:  duration: 1.550 ms
2014-11-18 17:46:48 CET LOG:  statement: SELECT surfids3_detail_add((0), '127.0.0.1', 64, 'style_css');

please can any one help me :)

**Comment by glaslos** [comment]
So you need a sensor address that's an IP address instead of a hostname/domain? But you want the actual IP address targeted?
Can you try:
```python
attack_event.sensor_addr = (socket.gethostbyname('www.google.com'), 80)
```

**Comment by katkad** [comment]
No answer. I am closing this issue.
Reopen if still occures.
