### ISSUE TITLE
permission denied when try to start from docker

### ISSUE THREAD

**Issue by Wingless-Archangel** [mushorg/glastopf#241]
I installed glastopf via docker command.

at first I run the command as mentioned in the documentation but failed to run it return as below:

```docker
FATA[0000] Error response from daemon: cannot bind mount volume: myhoneypot1 volume paths must be absolute. 
```

so I try to adjust the command and run as shown below:

```bash
docker run --name glastopf-honeypot --detach --publish 80:80 --volume /opt/wapphoneypot:/opt/myhoneypot glastopf
```

```python
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 5, in <module>
    pkg_resources.run_script('Glastopf==3.1.3-dev', 'glastopf-runner')
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 65, in <m
odule>
    GlastopfHoneypot.prepare_environment(args.workdir)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3_dev-py2.7.egg/glastopf/glastopf.py", line 215, in prepare_envir
onment
    os.path.join(work_dir, 'glastopf.cfg'))
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/opt/myhoneypot/glastopf.cfg'
Exception KeyError: KeyError(140144957503760,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

**Comment by glaslos** [comment]
What are the permissions on `/opt/myhoneypot`?

**Comment by katkad** [comment]
No answer. I am closing this issue.
Reopen if still occures.
