### ISSUE TITLE
Install Glastopf failed

### ISSUE THREAD

**Issue by royikle** [mushorg/glastopf#294]
Hi everyone.
I'm trying to install Glastopf on my vm, but I get two problem when I was installing.
1. It's always timeout when I use `sudo git clone git://github.com/mushorg/BFR.git` script.
2. I try to copy all of script from `https://github.com/mushorg/BFR` .
   Use `git clone https://github.com/mushorg/glastopf.git` to install Glastopf .
   After installing, I try to run Glastopf by `/usr/local/bin/glastopf-runner`.
   But it show error log like below:
`root@glastopf:/opt# /usr/local/bin/glastopf-runner
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 4, in <module>
    __import__('pkg_resources').run_script('Glastopf==3.1.3.dev0', 'glastopf-runner')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/EGG-INFO/scripts/glastopf-runner", line 15, in <module>
    from glastopf.glastopf import GlastopfHoneypot
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/glastopf.py", line 44, in <module>
    from modules.handlers.emulators.dork_list import mnem_service
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py2.7.egg/glastopf/modules/handlers/emulators/dork_list/mnem_service.py", line 18, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 92, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
Exception KeyError: KeyError(140302993555120,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
`

I also try MHN deploy script, but is show the same error message.
I have been google , but still not understand how to fix it.
Can somebody help me?

**Comment by hallmanhe** [comment]
try to use requests v2.20.0 to support for urllib3  in requirements.txt:

gevent>=1.0
webob>=1.2.0
pyopenssl
lxml
sqlalchemy>=0.8.0
jinja2
beautifulsoup>=3.2.0
requests==2.20.0
cssselect>=0.7.0
pymongo>=2.4
MySQL-python
hpfeeds
pylibinjection
libtaxii>=1.1
python-logstash
botocore

**Comment by royikle** [comment]
Thank you for your help.
But I don’t know where is the path of requirements.txt in Ubuntu.
Is the file in /bin/python2.7/... ?

**Comment by hallmanhe** [comment]
just try to update the  mushorg/glastopf/requirements.txt, and reinstall again

**Comment by royikle** [comment]
I just delete the old VM and rebuild it.
Copy BFR script from github.
Use git to get glastopf and change `requests>=1.0.0` to `requests==2.20.0`.
When I use `python setup.py install` ,It shows error log like below.
`
Installed /usr/local/lib/python2.7/dist-packages/idna-2.7-py2.7.egg
error: chardet 2.0.1 is installed but chardet<3.1.0,>=3.0.2 is required by set(['requests'])
`
For now chardet in requirements.txt is no version information.
Do I need to set` chardet==2.0.1` ?
